name: Publishing
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install -r requirements.txt
      - run: sudo apt install libsdl2-dev
      - run: pyxel package . main.py
      - run: pyxel app2html beehive-classic.pyxapp
      - run: mkdir dist
      - run: mv beehive-classic.html ./dist/index.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v3
      - id: deployment
        uses: actions/deploy-pages@v1
